name: " Supplementary Requirement"
description: "Yêu cầu phi chức năng (Non-functional requirements)"
title: "[SUP-XX] "
labels: ["SR"]
assignees: []

body:
  

  - type: dropdown
    id: category
    attributes:
      label: Loại yêu cầu (Requirement Type)
      options:
        - Hiệu năng trang sản phẩm
        - Bảo mật thanh toán
        - Bảo mật tài khoản người dùng
        - Hiệu suất bộ lọc tìm kiếm
        - Độ khả dụng API vận chuyển
        - Độ chính xác AI đề xuất sản phẩm
        - Quy trình đặt hàng nhanh
        - Khả năng mở rộng hệ thống
        - Độ chính xác báo cáo và xuất file
        - Tuân thủ bảo mật dữ liệu người dùng
        - Cập nhật trạng thái đơn hàng real-time
        - Chatbot phản hồi nhanh
        
    

  - type: textarea
    id: description
    attributes:
      label: Mô tả 
      placeholder: "Trang danh sách và chi tiết sản phẩm phải tải trong < 2 giây với lưu lượng thông thường."
    

  
    

  - type: textarea
    id: related_features
    attributes:
      label: Feature liên quan
      description: "Các Feature chịu ảnh hưởng bởi yêu cầu này"
      placeholder: "FEAT-01, FEAT-02"

  - type: dropdown
    id: priority
    attributes:
      label: Priority (Độ ưu tiên)
      options:
        - High
        - Medium
        - Low
    

  - type: dropdown
    id: status
    attributes:
      label: Status
      options:
        - Proposed
        - In Progress
        - Implemented
        - Verified
        - Done

        
  - type: dropdown
    id: difficulty
    attributes:
      label: Difficulty (Độ khó)
      options:
        - Low
        - Medium
        - High

  - type: dropdown
    id: stability
    attributes:
      label: Stability (Độ ổn định)
      options:
        - Ổn định
        - Có thể thay đổi

  - type: input
    id: assigned_to
    attributes:
      label: Assigned to (Nhóm phụ trách)
      placeholder: "Nhóm Backend"

  - type: dropdown
    id: cost
    attributes:
      label: Cost (Chi phí ước lượng)
      options:
        - Low
        - Medium
        - High
